name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main  # Triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Fetches the code from the repository

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your_dockerhub_username/your_app_name:latest .

      - name: Push Docker image to Docker Hub
        run: docker push your_dockerhub_username/your_app_name:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures deploy runs after build
    steps:
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy Docker container to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull your_dockerhub_username/your_app_name:latest
            docker stop your_container_name || true
            docker rm your_container_name || true
            docker run -d -p 80:80 --name your_container_name your_dockerhub_username/your_app_name:latest
          EOF
