name: Build and Deploy Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow from the Actions tab

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository to get access to your code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub (or another container registry)
      # Replace DOCKER_USERNAME and DOCKER_PASSWORD with your Docker credentials
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kaung19/sample_app:latest

      # SSH into the EC2 instance and deploy the Docker container
      - name: Deploy Docker container to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu  # The username for your EC2 instance (commonly "ubuntu" for Amazon AMIs)
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull kaung19/sample_app:latest
            
            # Stop and remove the existing container, if it exists
            docker rm -f my_container || true
            
            # Run the Docker container
            docker run -d --name my_container -p 80:80 kaung19/sample_app:latest
